# Learning and practicing NumPy with examples and exercises
## Presentado por: Omar Rodriguez Tolosa

# 1 Examples: NumPy

Ejemplo 1. Usamos el comando arr[2] para acceder a una posición de un vector, matriz, lista etc.

In [2]:
import numpy as np
#Basic Indexing:
arr = np.array([10, 20, 30, 40, 50])
print(arr[2]) # Output: 30

30


Ejemplo 2. Se usa el .array para crear una matriz o vector seguido de "[se incluyen los valores]"  y se usa el comando arr[1:4] para acceder a las posiciones dentro de un rango sin tomar en cuenta la posición final. en este caso la posción 4 es decir solo muestra el valor hasta la 3

In [30]:
#Slicing:
arr = np.array([10, 20, 30, 40, 50])
print(arr[1:4]) # Output: [20 30 40]

[20 30 40]


Ejemplo 3. Usamos el .array para crear la matriz seguido de "[se incluyen los valores]" y se usa el comando arr[1,2] para hacer una busqueda indicando el primer valor la fila y el segundo la columna el valor que se repita al selecionar esos dos conjuntos de valores es el resultado a imprimir

In [31]:
#Indexing 2D Arrays:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr[1, 2]) # Output: 6

6


Ejemplo 4. Con ete sucede lo mismo de buscar posiciones solo que al colocar arr[:2, 1:] lo que hacemos es filtar conjuntos de valores es decir si tenemos ":2" se va a leer todas las filas que esten antes de esta es decir la 1 y 0; Para el caso de "1:" se toman los valores de la columnas despues de la numero 1 

In [32]:
#Slicing 2D Arrays:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr[:2, 1:]) # Output: [[2 3] [5 6]]

[[2 3]
 [5 6]]


Ejemplo 5.  Se crean distintas matrices y con el comando tensor[1, 0, 2] accedemos a la matriz que se quiere seleccionar, accedemos a la fila y accedemos a la columna respectivamente y con el siguiente comando tensor[1] accedo a la matriz que deseo. podemos mirar cada matriz como si fueran un bloque parahacerlo ver de mejor manera es decir mi primer valor del comando me identifica el bloque(la matriz), el segundo la fila y el tercero la columna el valor que se repita en esas dos operaciones es el que se selecciona.

In [33]:
#3D Tensor Indexing:
tensor = np.array([[[1, 2, 3], [4, 5, 6]],
[[7, 8, 9], [10, 11, 12]],
[[13, 14, 15], [16, 17, 18]]])

# Access specific elements
print(tensor[1, 0, 2]) # Output: 9
# Access an entire "slice" (2D submatrix)
print(tensor[1]) # Output: [[ 7 8 9] [10 11 12]]

9
[[ 7  8  9]
 [10 11 12]]


Ejemplo 6. Se crea una matriz pero en este caso se le asignan valores con el comando .arange("numero hasta el cual se va a llenar la matriz") y el comando .reshape(3, 3, 3) es para indicar la cantidad de bloques (matrices), filas y columnas respectivamente. y con los comandos tensor[:, 1, :] y tensor[:, :, 2] accedo a filas y columnas de todos los bloques 

In [34]:
#Slicing a 3D Tensor:
tensor = np.arange(27).reshape(3, 3, 3)
# Slice along the first dimension
print(tensor[1]) # Output: 3x3 submatrix
# Slice along the second dimension
print(tensor[:, 1, :]) # Output: 3x3 matsubrix
# Slice along the third dimension
print(tensor[:, :, 2]) # Output: 3x3 submatrix

[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[ 3  4  5]
 [12 13 14]
 [21 22 23]]
[[ 2  5  8]
 [11 14 17]
 [20 23 26]]


Ejemplo 7. Se crea la misma matriz con la cantidad de valores que indique el comando .arange y con .reshape damos indicaciones de cuantos bloques, matrices, filas y columnas respectivamente. para este caso tiene 2 bloques cada uno con 3 matrices y cada matriz esta formada por 2 filas y 4 columnas. entonces cuando se usa el comando tensor[1, 2, 0, 3] accedemos a el bloque 1, la matriz 2, la fila 0 y la columna 3 respectivamente.

In [35]:
#4D Tensor Indexing:
tensor = np.arange(48).reshape(2, 3, 2, 4)
# Access specific elements
print(tensor[1, 2, 0, 3]) # Output: 47
# Access a whole "block" (3D sub-tensor)
print(tensor[1, 2]) # Output: 2x4x3 sub-tensor

43
[[40 41 42 43]
 [44 45 46 47]]


Ejemplo 8. Se crea la misma matriz con la cantidad de valores que indique el comando .arange y con .reshape damos indicaciones de cuantos bloques, matrices, filas y columnas hay respectivamente. para este caso tiene 2 bloques cada uno con 3 matrices y cada matriz esta formada por 2 filas y 4 columnas. entonces cuando se usa el comando tensor[:, 2, :, :] accedemos a todos los bloques, a la matriz 2 de cada bloque y todas las filas y columnas respectivamente.

In [36]:
#Slicing a 4D Tensor:
tensor = np.arange(48).reshape(2, 3, 2, 4)
# Slice along the first dimension
print(tensor[1]) # Output: 3x2x4 sub-tensor
# Slice along the second dimension
print(tensor[:, 2, :, :]) # Output: 2x2x4 sub-tensor
# Slice along the third dimension
print(tensor[:, :, 0, :]) # Output: 2x3x4 sub-tensor

[[[24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]]

 [[40 41 42 43]
  [44 45 46 47]]]
[[[16 17 18 19]
  [20 21 22 23]]

 [[40 41 42 43]
  [44 45 46 47]]]
[[[ 0  1  2  3]
  [ 8  9 10 11]
  [16 17 18 19]]

 [[24 25 26 27]
  [32 33 34 35]
  [40 41 42 43]]]


EJemplo 9. Se asignan variables A y B y dentro de estas se incluyen matrices de 2x2 y luego se crea una variable result en la cual se le asigna una operación entre matrices. hay que tener en cuenta que esta suma solo se debe realizar si las matrices son de igual tamaño.

In [37]:
#Matrix Addition:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
result = A + B
print(result)

[[ 6  8]
 [10 12]]


Ejemplo 10. Se usa el comando .dot para realizar multiplicación en este caso para multiplicación de matrices es decir AxB.

In [38]:
#Matrix Multiplication:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
result = np.dot(A, B)
print(result)

[[19 22]
 [43 50]]


Ejemplo 11. Se usa el comando .transpose para encontrar la transpuesta de matrices es decir el cambio de filas por columnas o viceversa en una matriz. es decir los valores si tengo una matriz 3x2 la transpuesta de esa matriz va a resultar una matriz 2x3.       

In [39]:
#Transpose of a Matrix:
A = np.array([[1, 2], [3, 4]])
result = np.transpose(A)
print(result)

[[1 3]
 [2 4]]


Ejemplo 12. Se usa los comandos .linalg.det y .linalg.inv para obtener el determinante y la inversa de una matriz respectivamente. 

In [40]:
#Matrix Determinant and Inverse:
A = np.array([[1, 2], [3, 4]])
det = np.linalg.det(A)
inverse = np.linalg.inv(A)
print("Determinant:", det)
print("Inverse:\n", inverse)

Determinant: -2.0000000000000004
Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]


Ejemplo 13. El código calcula los autovalores y autovectores de la matriz cuadrada `A` utilizando `np.linalg.eig()`, lo cual permite identificar los factores escalares (`eigenvalues`) y las direcciones (`eigenvectors`) que no cambian cuando se aplica la transformación lineal representada por `A`; es decir, encuentra los vectores que solo se escalan (no se rotan) al multiplicarlos por la matriz.

In [ ]:
#Eigenvalues and Eigenvectors:
A = np.array([[1, -1], [1, 3]])
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues: [2.00000002 1.99999998]
Eigenvectors:
 [[-0.70710677 -0.70710679]
 [ 0.70710679  0.70710677]]


Ejemplo 14. El código resuelve un sistema de ecuaciones lineales de la forma A * x = b utilizando `np.linalg.solve()`, donde `A` es la matriz de coeficientes y `b` es el vector de resultados; la función encuentra el vector `x` que satisface simultáneamente todas las ecuaciones del sistema, proporcionando la solución exacta si la matriz es cuadrada e invertible.

In [ ]:
#Solving Linear Equations:
A = np.array([[2, 1], [1, 1]])
b = np.array([3, 2])
solution = np.linalg.solve(A, b)
print("Solution:", solution)

Solution: [1. 1.]


Ejemplo 15. 

In [ ]:
# Generate some sample data
np.random.seed(0)
X = 2 * np.random.rand(100, 1)
y = 4 + 3 * X + np.random.randn(100, 1)
# Add bias term to X
X_b = np.c_[np.ones((100, 1)), X]
# Hyperparameters
learning_rate = 0.1
n_iterations = 1000
# Initialize the parameters
theta = np.random.randn(2, 1)
# Gradient Descent
for iteration in range(n_iterations):
gradients = 2 / 100 * X_b.T.dot(X_b.dot(theta) - y)
theta = theta - learning_rate * gradients
print("Final theta:", theta)

# 2 Examples: Python functions and classes

Ejemplo 1. Se crea una función llamada greet que recibe un parametro llamado name al recibir este parametro retorna un saludo personalizado concatenando "Hello, " con el nombre dado y un signo de exclamación al final. Luego, se llama a la función con el argumento "Ana" y se imprime el resultado.

In [ ]:
#Simple Function:
def greet(name): 
    return "Hello, " + name+"!"
print(greet("Ana")) # Output: Hello, Ana!

Hello, Ana!


Ejemplo 2. Se crea una función llamada add_numbers que recibe dos parametros a y b respectivamente se hace una operación de suma a esos dos parametros y retorna el resultado de esa operación.

In [60]:
#Function with Parameters and Return:
def add_numbers(a, b):
    sum = a + b
    return sum
result = add_numbers(5, 7)
print(result) # Output: 12

12


Ejemplo 3. Se crea una función que calcula la potencia de un número. tiene dos parametros base y exponent donde el exponent esta predefinido como =2 es decir la operación siempre se va a elevar a la 2 mientras este valor predeterminado no sea cambiado como es el caso del primer print, solo va hacer cambiada si yo lo requiero. esto permite facilidad y practicidad a la hora de realizar distintas operaciones sin necesidad de cambiar mucho el codigo. 

In [65]:
#Function with Default Parameter:

def power(base, exponent=2):
    return base ** exponent
print(power(3)) # Output: 9
print(power(2, 3)) # Output: 8

9
8


Ejemplo 4. Se crea una funcion que recibe como parametro numbers el cual retorna el minimo y maximo valor de este. luego se crea una lista y a esa lista la llamo junto a la función para que me encuentre el maximo y minimo de esa lista llamada nums y la guardo en la variable minium, maxium que luego la imprimo y se obtiene como resultado el minimo y maximo valor de la lista nums.

In [66]:
#Function with Multiple Returns:
def min_max(numbers):
    return min(numbers), max(numbers)
nums = [4, 9, 2, 7, 5]
minimum, maximum = min_max(nums)
print(minimum, maximum) # Output: 2 9

2 9


Ejemplo 5. Se crea una función llamada area_of_rectangle cuyos parametros son largo y ancho y la función lo que hace es calcular el area de un rectangulo dependiendo de los parametros que se le asignen y retorna el resultado.

In [75]:
#Function with Docstring:
def area_of_rectangle(length, width):
    """
    Calculates the area of a rectangle.
    Args:
        length (float): The length of the rectangle.
        width (float): The width of the rectangle.
    Returns:
    float: The area of the rectangle.
    """
    return length * width
area= area_of_rectangle(3,2)
print (area)

6


Ejemplo 6. El código define una clase llamada `Dog` que modela a un perro con dos atributos: nombre y edad. Al crear una instancia de la clase, el constructor `__init__` inicializa estos valores. Además, la clase incluye un método llamado `bark` que imprime un mensaje indicando que el perro está ladrando. Finalmente, se crea un objeto `dog1` con nombre "Buddy" y edad 3, y al llamar a `dog1.bark()`, se muestra el mensaje "Buddy is barking!".

In [74]:
#Creating a Simple Class:
class Dog:
    def __init__(self, name, age):
        self.name = name
        self.age = age
    def bark(self):
        print(f"{self.name} is barking!")
# Create an instance of the Dog class
dog1 = Dog("Buddy", 3)
dog1.bark() # Output: Buddy is barking!

Buddy is barking!


Ejemplo 7. Este código define una clase `Student` que representa a un estudiante con nombre, edad y una lista de calificaciones. Permite agregar notas mediante el método `add_grade` y calcular el promedio de las calificaciones con `get_average_grade`. Se crea una instancia del estudiante llamado "Alice", se le asignan dos notas (85 y 92), y luego se imprime su promedio.

In [ ]:
#Adding Methods and Attributes
class Student:
    def __init__(self, name, age):
        self.name = name
        self.age = age
        self.grades = []
    def add_grade(self, grade):
        self.grades.append(grade)
    def get_average_grade(self):
        return sum(self.grades) / len(self.grades)
# Create a Student instance and add grades
student1 = Student("Alice", 18)
student1.add_grade(85)
student1.add_grade(92)
average_grade = student1.get_average_grade()
print(f"{student1.name}’s average grade: {average_grade}")

Alice’s average grade: 88.5


## 3 Exercise
Para este apartado se resolveran todos los ejercicios planteados en el documento taller 1 [Material NumPy - Ejercicios y Ejemplos](https://drive.google.com/drive/u/1/folders/15X399KrWXIGp1qvD1B5LMBnqcFswEn96). Lo ejercicios se resolveran todos en su orden asignado es decir en la parte superior de cada consola estara el inciso seguido de la solución se debe tener en cuenta que para poder visualizar la respuesta es necesario ejecutar el codigo de la consola. 


3.1 Indexing Arrays in NumPy
1. Given the NumPy array arr = np.array([3, 7, 1, 9, 5]), perform
the following indexing operations:

    a) Retrieve the third element of the array.

    b) Slice the array to get elements from index 1 to index 3.
        
    c) Change the value of the fourth element to 12.

In [18]:
arr = np.array([3, 7, 1, 9, 5])
# Inciso a
print ("EL valor del elemento 3 de la matriz es: ", arr[3])
# Inciso b
print("Los valores del indice 1 al 3 son: ",arr[1:4])
# Inciso c
arr[3]=12
print(arr)

EL valor del elemento 3 de la matriz es:  9
Los valores del indice 1 al 3 son:  [7 1 9]
[ 3  7  1 12  5]


2. Create a 2D NumPy array matrix with the following values:

[1 2 3

4 5 6

7 8 9]


a) Retrieve the element in the second row and third column.

b) Slice the matrix to get the submatrix consisting of the first two rows
and all columns.

In [11]:
matriz=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(" a) El elemento de la segunda fila y tercera columna es : ",matriz[2, 2])
print(" b) la submatriz que consta de las dos primeras filas y todas las columnas es :",matriz[:2, :3])

 a) El elemento de la segunda fila y tercera columna es :  9
 b) la submatriz que consta de las dos primeras filas y todas las columnas es : [[1 2 3]
 [4 5 6]]


3.2 Indexing and Slicing Higher-Dimensional Tensors
Consider the following 3D tensor representing a stack of matrices:

tensor =

1 2 3 4
5 6 7 8
9 10 11 12
 ,

13 14 15 16
17 18 19 20
21 22 23 24
,

25 26 27 28
29 30 31 32
33 34 35 36

1. Retrieve the element at the position (1, 0, 2) within the tensor.
2. Slice the tensor to obtain the 3 × 4 sub-tensor that corresponds to the
second “matrix” (slice) along the first dimension.
3. Slice the tensor to obtain the 2×4 sub-tensor that corresponds to the last
row of the last two “matrices.”
4. Retrieve the element at the position (2, 1, 3) within the tensor.
5. Slice the tensor to obtain the 2×4 sub-tensor that corresponds to the first
row of the las two “matrices.”
Hint: Remember that in NumPy indexing, the first index corresponds to the
outermost dimension, the second index corresponds to the next inner dimension,
and so on.

In [ ]:
import numpy as np

tensor = np.array([
    [  # Primera matriz
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12]
    ],
    [  # Segunda matriz
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]
    ],
    [  # Tercera matriz
        [25, 26, 27, 28],
        [29, 30, 31, 32],
        [33, 34, 35, 36]
    ]
])

print(tensor[1,0,2])
#print(tensor[1])
print(tensor[0:, 2, 3 ])

15


IndexError: index 4 is out of bounds for axis 2 with size 4